justeattakeaway/pie-aperture

vanilla-app/.gitignore
vanilla-app/main.js
vanilla-app/package.json
vanilla-app/yarn.lock

- Updated to use `pie-switch` instead of `pie-toggle-switch`
- Updated `pie-card` instead of `pie-card-container`
- Updated versions of all other components
- Installed missing dependencies
- Updated main.js to correctly use icons, new component names and added a button to the modal

chore(vanilla-app): DSW-000 update to latest package versions

---

nextjs-app/package.json
nextjs-app/src/pages/index.tsx
nextjs-app/yarn.lock
vanilla-app/main.js
vanilla-app/package.json
vanilla-app/yarn.lock

Adds Pie Form Label to Vanilla and nextjs app.

Add form label to vanilla and nextjs app.

---

nextjs-app/package.json
nextjs-app/src/pages/form.tsx
nextjs-app/src/pages/index.tsx
nextjs-app/test/nextjs.spec.js
nextjs-app/yarn.lock
vanilla-app/form.html
vanilla-app/form.js
vanilla-app/index.html
vanilla-app/main.js
vanilla-app/package.json
vanilla-app/test/vanilla.spec.js
vanilla-app/vite.config.js
vanilla-app/yarn.lock

Adds form pages to both vanilla and nextjs apps that demonstrate the pie-switch component within a form.

feat(pie-aperture): DSW-1381 use latest switch and cookie banner and add form pages

---

README.md

- Added links to deployments in pie aperture readme

docs(pie-aperture): DSW-000 added links to deployments in readme

---

nextjs-app/package.json
vanilla-app/package.json

- Adds script for upgrading all Pie dependencies at once to the latest version

feat(pie-aperture): DSW-000 add script for upgrading Pie dependencies

---

nextjs-app/package.json
nextjs-app/src/pages/index.tsx
nextjs-app/yarn.lock
vanilla-app/main.js
vanilla-app/package.json
vanilla-app/yarn.lock

Add PIE TAG to both applications.

DSW-1522 add pie tag

---

.github/actions/amplify-teardown/action.yml
.github/workflows/build.yml
.github/workflows/closed.yml
.github/workflows/handle-closed-prs.yml

This PR fixes the issue where `main` wasn't being deployed, and copies the actions from PIE to teardown preview GH environments / amplify branches.

ci: DSW-1602 deploy on main & teardown preview envs

---

vanilla-app/components/assistive-text.html
vanilla-app/components/button.html
vanilla-app/components/card.html
vanilla-app/components/chip.html
vanilla-app/components/cookie-banner.html
vanilla-app/components/form-label.html
vanilla-app/components/icon-button.html
vanilla-app/components/link.html
vanilla-app/components/modal.html
vanilla-app/components/spinner.html
vanilla-app/components/switch.html
vanilla-app/components/tag.html
vanilla-app/package.json
vanilla-app/partials/page.html
vanilla-app/vite.config.js
yarn.lock

[Added] - Basic templating to Vite in the vanilla app to get rid of duplicated markup

feat: DSW-000 add basic templating to vanilla app

---

nextjs-app/package.json
nextjs-app/src/pages/integrations/form.tsx
nuxt-app/package.json
nuxt-app/pages/integrations/form.vue
test/playwright/page-objects/form.page.ts
test/system/form.spec.ts
vanilla-app/integrations/form.html
vanilla-app/js/form.js
vanilla-app/package.json
yarn.lock

Adds the new number input type to the Aperture app form pages and updates the browser test to include it.
Updates to latest `pie-input`

dsw-1591: add number input to form page and tests

---

.github/workflows/pie-trigger.yml

Attempting some things from this thread to trigger Aperture CI from PIE via repository_dispatch events - https://github.com/orgs/community/discussions/25219

chore: DSW-0 attempt to fix workflow trigger

---

nextjs-app/package.json
nextjs-app/src/pages/components/notification.tsx
nextjs-app/src/pages/index.tsx
vanilla-app/components/notification.html
vanilla-app/js/index.js
vanilla-app/js/notification.js
vanilla-app/package.json
yarn.lock

In this PR I am adding pie-notification into NextJS and Vanilla Apps.

feat: DSW-1463: Add component to pie aperture (NextJS & Vanilla)

---

.github/workflows/handle-closed-prs.yml

- Updated the `handle-closed-prs.yml` to support NextJS 14
This PR adds the teardown and deletion step for Next14 PR deployments. 
Once PRs are merged, this workflow triggers closing down active AWS deployments related to that PR.

ci: DSW-000 updated closed PRs yml to support nextjs 14

---

README.md

- Updated Aperture readme with NextJS links

docs: DSW-000 updated readme with new nextjs links

---

.github/workflows/handle-closed-prs.yml

- Updated pie bot token naming and positioning

ci: DSW-2146 updated handle-closed-prs.yml with token name and placing

---

.github/workflows/handle-closed-prs.yml

- Updated Amplify App IDs to correct IDs

ci: DSW-2146 updated amplify app id to correct id

---

.github/actions/amplify-teardown/action.yml

- Added Github app token retrieval

ci: DSW-2146 added github app token retrieval to action.yml

---

.github/workflows/handle-closed-prs.yml

- Updated the formatting of the workflow to include `pull_request`

ci: DSW-2146 updated formating and environment naming

---

.github/workflows/handle-closed-prs.yml

- added console logging for testing current output

ci: DSW-2146 added logging for testing purposes

---

.github/workflows/handle-closed-prs.yml

- Added command to show up to 100 previous environments in the list

ci: DSW-2146 updated environment list to show 100

---

.github/actions/amplify-teardown/action.yml
.github/workflows/handle-closed-prs.yml

- Removed unneeded get Github app id from actions workflow

ci: DSW-2146 fix amplify teardown 

---

nextjs-app-v13/src/pages/components/text-input.tsx
nextjs-app-v13/src/pages/index.tsx
nextjs-app-v13/test/visual/nextjs.spec.js
nextjs-app-v14/src/app/components/home-page.tsx
nextjs-app-v14/src/app/components/text-input/page.tsx
nextjs-app-v14/src/app/components/text-input/text-input.tsx
nextjs-app-v14/test/visual/nextjs.spec.js
nuxt-app/pages/components/text-input.vue
nuxt-app/pages/index.vue
nuxt-app/test/visual/nuxt.spec.js
vanilla-app/components/text-input.html
vanilla-app/js/index.js
vanilla-app/js/text-input.js
vanilla-app/test/visual/vanilla.spec.js

Adds a text-input component page to all apps

feat: dsw-1938 add text input page to all apps

---

.github/workflows/handle-closed-prs.yml

- Added Nuxt steps for PR teardown that removes PR + Amplify deployments

ci: DSW-2146 Updated closed prs yml to support Nuxt app

---

test/ssr/ssr.spec.ts

Adds two logs for debugging on CI failures.

Add two further logs for debugging purposes

---

nextjs-app-v13/src/pages/components/modal.tsx
nextjs-app-v13/src/pages/components/notification.tsx
nextjs-app-v14/src/app/components/modal/modal.tsx
nextjs-app-v14/src/app/components/notification/notification.tsx
nuxt-app/pages/components/modal.vue
nuxt-app/pages/components/notification.vue
nuxt-app/pages/index.vue
nuxt-app/test/visual/nuxt.spec.js
test/ssr/ssr.spec.ts
vanilla-app/js/modal.js
vanilla-app/js/notification.js

- Update notification and modal states in all apps
- Add notification component to Nuxt app
FYI: leading action for modal and notification component will be added after fix DSW-2208

feat: DSW-2142 Update notification and modal states in all apps

---

nextjs-app-v13/package.json
nextjs-app-v13/src/layout/navigation.tsx
nextjs-app-v13/src/pages/components/textarea.tsx
nextjs-app-v13/src/pages/index.tsx
nextjs-app-v13/test/visual/nextjs.spec.js
nextjs-app-v14/package.json
nextjs-app-v14/src/app/components/home-page.tsx
nextjs-app-v14/src/app/components/textarea/page.tsx
nextjs-app-v14/src/app/components/textarea/textarea.tsx
nextjs-app-v14/test/visual/nextjs.spec.js
nuxt-app/package.json
nuxt-app/pages/components/textarea.vue
nuxt-app/pages/index.vue
nuxt-app/test/visual/nuxt.spec.js
test/ssr/ssr.spec.ts
vanilla-app/components/textarea.html
vanilla-app/js/index.js
vanilla-app/js/textarea.js
vanilla-app/package.json
vanilla-app/test/visual/vanilla.spec.js
yarn.lock

Textarea component set up for all the apps

DSW-2214: initial textarea set up

---

wdio.conf.js

- Updated Percy Automate supported devices

refactor: DSW-0 Updated supported test devices

---

.github/workflows/ci-nuxtjs.yml
nuxt-app/pages/integrations/form.vue
test/playwright/page-objects/form.page.ts

- Enables the system tests on CI for the Nuxt app

enable Nuxt system tests in CI

---

nextjs-app-v14/src/app/integrations/form/form.tsx
nuxt-app/pages/integrations/form.vue
test/playwright/page-objects/form.page.ts
test/system/form.spec.ts
vanilla-app/integrations/form.html
vanilla-app/js/form.js

- Adds the Radio Group component to the existing Form tests
- Updates the values of the radio buttons to be favourite takeaways

DSW-000: update form tests to use radio group component

---

nextjs-app-v14/package.json
nextjs-app-v14/src/app/components/breadcrumb/breadcrumb.tsx
nextjs-app-v14/src/app/components/breadcrumb/page.tsx
nextjs-app-v14/src/app/components/home-page.tsx
nextjs-app-v14/test/visual/nextjs.spec.js
nuxt-app/package.json
nuxt-app/pages/components/breadcrumb.vue
nuxt-app/pages/index.vue
nuxt-app/test/visual/nuxt.spec.js
test/ssr/ssr.spec.ts
vanilla-app/components/breadcrumb.html
vanilla-app/js/breadcrumb.js
vanilla-app/js/index.js
vanilla-app/package.json
vanilla-app/test/visual/vanilla.spec.js
yarn.lock

adds the breadcrumb component to all apps

feat(pie-breadcrumb): DSW-3054 add the breadcrumb component

---

nextjs-app-v14/package.json
nuxt-app/package.json
vanilla-app/package.json
yarn.lock

updated pie packages to latest

update deps to latest

---

.github/workflows/ci-nextjs-v15.yml
nextjs-app-v15/src/app/components/home-page.tsx
nextjs-app-v15/src/app/components/toast-provider/page.tsx
nextjs-app-v15/src/app/components/toast-provider/toast-provider.tsx
nextjs-app-v15/src/app/integrations/controlled-form/controlled-form.tsx
nextjs-app-v15/src/app/integrations/controlled-form/page.tsx
nextjs-app-v15/src/app/integrations/uncontrolled-form/page.tsx
nextjs-app-v15/src/app/integrations/uncontrolled-form/uncontrolled-form.tsx
nextjs-app-v15/test/visual/nextjs.spec.js
nextjs-app-v15/wdio.conf.js
playwright-helpers/configuration-helper.js
test/system/form.spec.ts
webdriver-helpers/configuration-helper.js

Added the following to NextJS 15 app:
- Added Toast Provider page
- Added Controlled and Uncontrolled form pages
- Added system test support
- Added visual test support for related components
---
Mark items as `[-] N/A` if not applicable.

feat(pie-aperture): DSW-3178 Added Toast Provider, Controlled and Uncontrolled forms to NextJS 15

---

nextjs-app-v15/src/app/components/assistive-text/assistive-text.tsx
nextjs-app-v15/src/app/components/assistive-text/page.tsx
nextjs-app-v15/src/app/components/avatar/avatar.tsx
nextjs-app-v15/src/app/components/avatar/page.tsx
nextjs-app-v15/src/app/components/breadcrumb/breadcrumb.tsx
nextjs-app-v15/src/app/components/breadcrumb/page.tsx
nextjs-app-v15/src/app/components/home-page.tsx
nextjs-app-v15/test/visual/nextjs.spec.js

Added the following to NextJS 15 app:
- Added Assitive Text, Avatar and Breadcrumb pages
- Added visual test support for related components
---
Mark items as `[-] N/A` if not applicable.

feat(pie-aperture): DSW-3178 Added Assistive Text, Avatar and Breadcrumb Components to NextJS 15

---

nextjs-app-v15/src/app/components/home-page.tsx
nextjs-app-v15/src/app/components/textarea/page.tsx
nextjs-app-v15/src/app/components/textarea/textarea.tsx
nextjs-app-v15/src/app/components/thumbnail/page.tsx
nextjs-app-v15/src/app/components/thumbnail/thumbnail.tsx
nextjs-app-v15/src/app/components/toast/page.tsx
nextjs-app-v15/src/app/components/toast/toast.tsx
nextjs-app-v15/test/visual/nextjs.spec.js

Added the following to NextJS 15 app:
- Added Textarea, Thumbnail and Toast pages
- Added visual test support for related components
---
Mark items as `[-] N/A` if not applicable.

feat(pie-aperture): DSW-3178 Added Textarea, Thumbnail and Toast pages
